### ISSUE TITLE
Merging into mainline kernel?

### ISSUE THREAD

**Issue by qris** [walb-linux/walb-driver#5]
Is there a plan to get this merged into the mainline kernel? I saw [this mailing list post](https://groups.google.com/forum/#!topic/fa.linux.kernel/nxUzwMJzKIM) from 5 years ago, but nothing since then.

Could it help if this was converted to a device mapper plugin? Has this been investigated?

I think this would be really valuable for NAS developers and users, in a slightly different mode than it was designed for, which is placing the log on an SSD device and the data on hard disks (e.g. software/hardware RAID array). This should allow the hard disks to be spun down almost all the time, spinning up only when cache misses force it or the log is full. When the disks are up anyway, the log can be flushed in the background. This saves energy and reduces noise, which are good in home and server environments. I didn't see a comparison to [dm-cache](https://en.wikipedia.org/wiki/Dm-cache) in the documentation, which might also work for this purpose.

In order for this to work, it would held if there was a read cache as well (as the OS block cache is limited to free RAM, so not huge). This could perhaps be layered on top of the WALB device, using a separate cache device, or could be integrated by using free space on the log device for read cache blocks, invalidating them when overwritten by the log.

**Comment by starpos** [comment]
Thank you for your interests and comments.

WalB aims consistent backup of online block devices primarily
and it is used in our production cloud service now.

Write-back cache functionality is not implemented now and we do not have a plan to develop it,
while it is a nice idea because WalB logs can be dealt with as write-back cache immediately.
(Read IO forwarding code and online redo code are required to achieve it.)
Additional read cache functionality is also nice idea...

Besides, we do not have plans to develop device mapper version of WalB
or to merge WalB driver to the upstream kernel, because they require much cost and effort.

If you need such software, I recommend other ones or developing it by yourself.
How about dm-writeboost?
https://github.com/akiradeveloper/dm-writeboost
It has write-back cache but does not have consistent backup functionality.
I do not know details of dm-cache...

Of course, we are welcome nice patches for WalB.
